# Site settings
title: 3
email: MarkBruns@MarkBruns.com
description: This is for 3) RockRapids.GUIDE ... the others in this ecosystem of apps are 0) INFO 1) ART, 2) FUN, 4) SHOP, 5) STORE, 6) WORK, 7) XYZ
twitter_username: MarkBruns
github_username:  RockRapids

# Build settings
markdown: kramdown
